project_id = "ogckvnnwngfndlhxolue"

[functions.verify-admin]
verify_jwt = false

[functions.delete-own-account]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.generate-love-message]
verify_jwt = false

[functions.check-password]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = false

[functions.log-security-event]
verify_jwt = false

[functions.track-page-view]
verify_jwt = false

[functions.get-users-with-emails]
verify_jwt = false

[functions.track-donation-event]
verify_jwt = false
