project_id = "ogckvnnwngfndlhxolue"

[functions.verify-admin]
verify_jwt = false

[functions.delete-own-account]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.generate-love-message]
verify_jwt = false
